#!/bin/bash
set -euo pipefail
# shellcheck source=common.sh
source "$(dirname "$0")/common.sh"

msg "creating container for holding test data volumes"
cid=$(docker create -v /data --name testdata busybox)

cleanup_container() {
  docker rm -f "$cid" >/dev/null && msg "cleaned up container $cid" || msg "failed to clean up container $cid"
}
trap cleanup_container EXIT

gunzip -fk test/testdata.fds.pb.gz
docker cp test/testdata.fds.pb testdata:/data

msg "running a build using $image"
docker run --rm --volumes-from testdata "$image" -i /data/testdata.fds.pb -o /data/testoutput

msg "transferring output from test data volume"
rm -rf testoutput
docker cp testdata:/data/testoutput testoutput
cleanup_container

test_tag=proto-registry-test-$(uuidgen)
msg "attempting to build the resulting deploy Docker image"
docker build -t "$test_tag" testoutput

msg "starting built docker image..."
cid=$(docker run --rm -d -p 80 "$test_tag")

type_url=http://localhost:80/google.protobuf.Any
msg "trying to fetch binary schema at $type_url"
docker run --rm --network container:"$cid" appropriate/curl -H 'Accept: application/protobuf' "$type_url" | protoc --decode google.protobuf.Type /usr/include/google/protobuf/type.proto

msg "trying to fetch HTML schema at $type_url"
docker run --rm --network container:"$cid" appropriate/curl -H 'Accept: text/html' -i "$type_url"
echo >&2

msg "success!"
